Feature read and execute commands 15 - v. 0.1.0 Candidate
StatCan/tass-ssat pull request #26
Opened 2023-03-09 20:52 UTC by ty-desj

With this feature added, all basic functions are available for a minimally viable product.

2023-03-09 21:05 UTC, ty-desj commented
@DominicParent after closing/merging the 2 open PR I feel comfortable calling this version 0.1.0. What are your thoughts?

2023-03-09 22:24 UTC, DominicParent commented
@ty-desj Sounds good to me, it'd be nice if we could do the next testing we had talked about with v0.1.0. We'd get good feedback to evolve the data model and other features of the application.

FYI, this PR is still marked as a draft/WIP. Once you promote it, let me know so that I can review and approve.

2023-03-10 14:40 UTC, DominicParent requested changes
If conftest.py and tass_sample.json are in the root folder, they will not be built into the package. Only files in the tass folder are built in the package.

Please make the necessary modifications for test data to be in the tests folder and the functionality to be in the tass folder.

2023-03-14 13:55 UTC, DominicParent approved these changes

2023-03-14 13:55 UTC, merged