Feature 54 implement window switch
StatCan/tass-ssat pull request #62
Opened 2023-05-08 15:25 UTC by ty-desj

Added switch to window by title. Defaults to switch to next window if no title given. Raises exception if window not found.

2023-05-08 16:10 UTC, DominicParent commented on src/tass/actions/selenium.py
> +    raise ValueError('No window with title: {}'.format(title))
@ty-desj judging by the Python docs, ValueError seems fine. What do you not like about it?

2023-05-08 16:12 UTC, ty-desj commented on src/tass/actions/selenium.py
> +    raise ValueError('No window with title: {}'.format(title))
I am thinking about for error handling purposes, whether we want to be able handle this error in a unique way or treat it like any other error.

2023-05-08 17:22 UTC, ty-desj commented on src/tass/actions/selenium.py
> +    raise ValueError('No window with title: {}'.format(title))
I am comfortable leaving this as is for now, I can't come up with any reasonable reason that this particular error would need to be treated differently. Review at your convenience :smiley:

2023-05-09 17:35 UTC, DominicParent requested changes
Please resolve flake8 issues:
./src/tass/actions/selenium.py:271:1: W293 blank line contains whitespace
./src/tass/actions/selenium.py:274:62: W291 trailing whitespace
./src/tass/actions/selenium.py:276:1: W293 blank line contains whitespace
./src/tass/actions/selenium.py:283:67: W291 trailing whitespace
./src/tass/actions/selenium.py:285:1: W293 blank line contains whitespace

2023-05-09 17:57 UTC, DominicParent approved these changes

2023-05-09 18:09 UTC, merged